- src/lib.rs
Based on PR #7. Fixes issue #4. r? @SimonSapin
> Fix issues found in initial review

- Cargo.toml
- README.md
- src/lib.rs
r? @SimonSapin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/14)
> Documentation and README updates

- src/lib.rs
This is the first part of the fix for #8, and fixes servo/servo#6978.
r? @SimonSapin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/15)
> Move W7 into a separate pass

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/18)
> Version 0.2.2

- src/lib.rs
Was showing up in profiles.
r? @mbrubeck
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/21)
> Inline `is_rtl`

- .gitignore
- Cargo.toml
don't package these
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/25)
> Ignore text files

- .gitignore
- .rustfmt.toml
- src/char_data/mod.rs
- src/explicit.rs
- src/implicit.rs
- src/lib.rs
- src/prepare.rs
* Add .rustfmt.toml and format all files
* [src] Update Copyright notice in .rs files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/29)
> Auto-format all files and update Copyright notice

- .travis.yml
Example run: https://travis-ci.org/behnam/rust-unicode-bidi/jobs/232979295
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/32)
> [travis.yml] Add build script for new `with_serde` feature

- .travis.yml
- Cargo.toml
- src/lib.rs
- tests/conformance_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/34)
> Support Rust 1.15

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/37)
> Bump version to 0.3.3

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/48)
> Add CI badges for crates.io

- .github/workflows/main.yml
> Update MSRV to 1.36.0.

- src/lib.rs
Create a function that exactly match `ubidi_reorderVisual`
> add reorder_visual fn

- src/lib.rs
This is a comment that I left in #80 which seems to have been overlooked.
https://github.com/servo/unicode-bidi/pull/80/files#r930147101
CC @younies @Manishearth
> Simplify reorder_visual()

- src/lib.rs
> serde tests require hardcoded-data feature

- Cargo.toml
After this I'm going to update the Unicode  version and cut another release
> Bump to 0.3.9

- Cargo.toml
Release with the new Unicode 15 data
> Bump to 0.3.10

- Cargo.toml
Contains https://github.com/servo/unicode-bidi/pull/98
> Bump to 0.3.11

- src/lib.rs
> Fix out of bounds panic

- src/lib.rs
This aims to boost performance for paragraphs that do not contain any strongly-RTL characters.
Typical results of `cargo bench -F bench_it --bench udhr` with current master:
test bench_1_bidi_info_new_for_ltr_texts  ... bench:     891,763 ns/iter (+/- 43,823)
test bench_2_bidi_info_new_for_bidi_texts ... bench:   1,002,740 ns/iter (+/- 173,182)
test bench_3_reorder_line_for_ltr_texts   ... bench:     155,455 ns/iter (+/- 17,878)
test bench_4_reorder_line_for_bidi_texts  ... bench:     330,877 ns/iter (+/- 39,449)
And the same test after applying this patch:
test bench_1_bidi_info_new_for_ltr_texts  ... bench:     875,862 ns/iter (+/- 99,252)
test bench_2_bidi_info_new_for_bidi_texts ... bench:   1,005,841 ns/iter (+/- 179,152)
test bench_3_reorder_line_for_ltr_texts   ... bench: …
> Optimize handling of purely-LTR paragraphs

- src/lib.rs
This is a lightweight function equivalent to ICU's ubidi_getBaseDirection, which just determines the base direction of a piece of text. This is intended for use when the caller just wants the base directionality, and no further bidi processing will be required.
Returns Direction::Ltr or Direction::Rtl according to the first strong character (bidi type L, R, or AL) found in the text (outside of isolate embeddings).
If no strong character is found, returns Direction::Mixed (meaning Neutral in this context, but to avoid breaking API compatibility I didn't want to add a Neutral value to the Direction enum, and creating a new BaseDirection enum here seemed like overkill).
> [base-dir] Add a function to get the base direction of a text

- Cargo.toml
We have a spec-compliance fix and an added API.
> Bump version to 0.3.15
