servo/unicode-bidi

src/lib.rs

I thought this wasn't needed for Servo, since paragraphs in HTML are (normally) based on markup, so Servo can usually just process one paragraph at a time.  However, for preformatted text, the bidi algorithm must handle multiple paragraphs in a single inline flow.
The important changes here are in `process_text` and `initial_scan`.  Most of the other changes are just renaming variables and functions to make sense in a multi-paragraph world.
`process_text` no longer returns the max embedding level.  This was intended for optimizations, but wasn't actually useful in Servo.  An approach like #5 can provide a replacement for this optimization.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/12)

Handle multiple paragraphs in input text.

---

src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/17)

Fix ParagraphInfo for unusual paragraph separators.

---

Cargo.toml

The code features unicode version 8.0.0, but version 0.2.2 is still on unicode 7.0.0
I ended up having to look at the code to realise what's wrong :)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/23)

Version 0.2.3

---

src/lib.rs

Fix compile warning:
```
warning: unused import: `is_rtl`
--> src/lib.rs:353:28
|
353 |     use super::{BidiClass, is_rtl};
|                            ^^^^^^
|
= note: #[warn(unused_imports)] on by default
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/26)

Fix warning: unused import

---

AUTHORS
src/char_data/mod.rs
src/explicit.rs
src/format_chars.rs
src/implicit.rs
src/level.rs
src/lib.rs
src/prepare.rs
tests/conformance_tests.rs
tools/generate.py

Initial results: `60494 test cases failed! (196253 passed)`
Because of the current limitations of rust's test framework, and the huge number of failures, the base (not including matching pairs) conformance test is executed in one run, and a summary is panic'ed (if there's any failure) and for the integration test to pass, it's marked as `should_panic`, with summary of the test run as `expected` string.
Fix #1 
To be able to implement L1, we need access to more information from
`BidiInfo`, namely `original_classes` of the `text`, in `visual_runs()`,
which would mean it should pass through `reorder_line()`.
The fact that information from `BidiInfo` is needed for both steps of
the public API (generating `BidiInfo` and consuming it
per-paragraph/per-level) made me change the API design and …

Add Conformance Test and implement L1 rule

---

Cargo.toml
src/deprecated.rs
src/level.rs
src/lib.rs

Add `with_serde` feature, which implements serde for the new `struct
Level`, mainly used in `servo`, supporting serde `0.8`, `0.9` and `1.0`.
Add tests for the `with_serde` feature.  The `serde_tests` modules only
works for `serde:>=1.0`, though.
`servo` has dependency on the loose implementation of `visual_runs()`,
which couldn not be improved without breaking the API, as it needs more
information to process the levels correctly, and the call-site in
`servo` does not have all the information needed and needs a non-trivial
change to work with the new improved version. Therefore, I have moved the
old version to a `deprecated` module, to be used for now until `servo`
is fixed and we drop the old implementation.
Bump version to `0.3.0`, as we now ready for a release: can build
`servo` (patch …

Add serde support and bump version to 0.3.0

---

benches/basic.rs
src/explicit.rs
src/format_chars.rs
src/implicit.rs
src/lib.rs
src/prepare.rs
tests/conformance_tests.rs

Continue my review of code based on spec and fix various steps that
drop the basic conformance failures from 12827 to 250.
* X10: Fix incorrect index for `succ_level` resolution (off by
`end_of_seq` because of sub-sequencing) and add unit tests from the spec
text, from both BD13 and X10 sections.
* N1/N2: Fix resetting rule for NI levels by definint `e`, as noted in
the spec.
* L1: Fix not resetting leading whitespace/formatting chars in a line.
* Use non-ASCII sample chars for `gen_char_from_bidi_class()`, which
increases the failure rate from 250 to 314.
* This allows easier testing of the logic, specially having specific cases
from the conformance test as unit test, as corner bugs unfold.
* There's almost no extra cost in expanding the shortcut condition to
check all the isolating run …

Improve basic conformance and add more unit tests

---

.travis.yml
examples/flame_udhr.rs
src/char_data/tables.rs
src/explicit.rs
src/lib.rs
tests/conformance_tests.rs

Firefox bumped their minimum so workarounds can be dropped.
https://bugzilla.mozilla.org/show_bug.cgi?id=1374807
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/41)

Rust 1.17.0

---

.appveyor.yml
.gitignore
.travis.yml
Cargo.toml
README.md
examples/flame_udhr.rs
src/char_data/mod.rs
src/char_data/tables.rs
src/deprecated.rs
src/explicit.rs
src/format_chars.rs
src/implicit.rs
src/level.rs
src/lib.rs
src/prepare.rs
tests/conformance_tests.rs
tools/generate.py

Summary: Development improvements, with no API or functionality changes.
* We already follow most of the items from the [Rust API guildeline](https://github.com/brson/rust-api-guidelines). In this stack, I fix one case that's fairly trivial and easily backward-compatible: use `serde` as feature name for enabling serde, instead of home-brew `with_serde`.
* The shortcut I put in `travis.yml` script section was causing false positives in 100% of executions (oops!), which is now fixed by a more verbose conditioning, but accurate.
* Add `appveyor.yml`, as many packages depending on this package already require stable windows builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/unicode …

Improve CI and update serde feature name

---

.travis.yml
Cargo.toml

* Upgrade to Unicode 10.0.0, released on 20 June 2017.
* Exclude data files and source files depending on data from crate package.
* Small fix for integration tests.
* Enable AppVeyor CI and improve Travis CI script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/45)

Bump version to 0.3.4

---

Cargo.toml
README.md

This will cause the README file to be displayed on crates.io.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/unicode-bidi/49)

Add readme field to Cargo manifest

---

src/lib.rs

The reset logic in visual runs doesn't take the line offset into account. The for loop iterates over the line's char indices, but the line-local index `i` is then used to index into the `original_classes` for the whole paragraph.
Consider the string `"aa טֶ"`, which consists of five chars with the following subranges:
- `0..1: a`
- `1..2: a`
- `2..3: space`
- `3..5: ט`
- `5..7: \u{5b6}`
What happens in detail: When resolving the line `3..7`, the code previously iterated over both chars, and for the last char `i=2` resolved to the original class of the space, setting `reset_from` to `Some(2)`. Then, all bytes from `2` to `line_str.len()` (which was `4`), were reset to paragraph level. As a result, the first half of `ט` was reset to `0`.
The result of all this is that the reordered visual …

Apply visual run resets to line range.

---

.travis.yml
Cargo.toml
examples/flame_udhr.rs
src/char_data/mod.rs
src/deprecated.rs
src/explicit.rs
src/implicit.rs
src/level.rs
src/lib.rs
src/prepare.rs
tests/conformance_tests.rs

This increases the minimum supported Rust version from 1.17 to 1.31 (released in December 2018).  I hope this will have little impact on users, since this version of Rust is almost 2.5 years old, and because our main downstream crates (`url` and `postgres-protocol`) already require 1.31 or later.
Many of the changes below are fixing new rustc/clippy warnings added in recent toolchains.
r? @Manishearth

Update to 2018 edition and fix warnings

---

Cargo.toml
examples/flame_udhr.rs
src/explicit.rs
src/implicit.rs
src/level.rs
src/lib.rs
src/prepare.rs

The old version was implemented as a compiler plugin for very old nightly rustc builds.  The new versions are compatible with stable Rust.
r? @Manishearth

Update to flame 0.2 and flamer 0.4

---

Cargo.toml
src/char_data/mod.rs
src/deprecated.rs
src/explicit.rs
src/implicit.rs
src/level.rs
src/lib.rs
src/prepare.rs

Because of the matches crate, to actually be used on `no_std` targets, this requires either:
- https://github.com/SimonSapin/rust-std-candidates/pull/23
- That we bump the MSRV to 1.42.0
- That we change usage of the `matches!` macro
I opted for the last option here, but feel free to only take the first commit (which still compiles fine even though the subcrate isn't marked `no_std`, but downstream users will just get an error that they tried to link to std).

Add `no_std` support

---

Cargo.toml

Would release #57 and #58, neither contain breaking changes.

Bump version to 0.3.6

---

.github/workflows/main.yml
Cargo.toml
src/lib.rs

Fixes a typo that I introduced in #58, which effectively disabled the entire crate when the default `std` feature was disabled.
Also, now we actually test the `no_std` support, so things like this shouldn't happen again.

Fix `no_std`

---

.github/workflows/main.yml
Cargo.toml
src/char_data/mod.rs
src/char_data/tables.rs
src/data_source.rs
src/lib.rs
tests/conformance_tests.rs
tools/generate.py

Adds a trait that makes the data pluggable, and defines a default `hardcoded-data` feature.
We shouldn't release this just yet, I'd like to also perform a Unicode 14 update.
cc @younies

Add pluggable data

---

Cargo.toml
README.md

- Use SPDX license format
- Remove Travis CI reference and replace with GitHub Actions badge
- Use HTTPS for link

Update Readme and Cargo.toml

---

.github/workflows/main.yml

Eg: https://github.com/servo/unicode-bidi/actions/runs/2037210406

Add missing platform for fmt CI.

---

src/lib.rs

In order to implement data_source, we need to make `mod data_source` public.

Make data_source public.

---

Cargo.toml

The hardcoded data stuff doesn't actually include breaking changes since it's purely new APIs (though it may affect people running with `default-features = false` unfortunately), happy to make it 0.4 instead.

Bump to 0.3.8

---

src/implicit.rs
src/lib.rs
tests/conformance_tests.rs

Progress on #90
The multibyte thing was found whilst investigating https://github.com/servo/unicode-bidi/issues/86. It's not necessarily the best way to do it, but it does fix some tests, and it's probably the best path forward until we know what we're doing in https://github.com/servo/unicode-bidi/issues/86

Fix W2 rule ordering; behavior of multibyte characters in W4

---

src/data_source.rs
src/explicit.rs
src/implicit.rs
src/lib.rs
src/prepare.rs
tests/conformance_tests.rs

Built on top of https://github.com/servo/unicode-bidi/pull/91. PR starts at "Add all fixups for retaining explicits".
Fixes #89 by doing the implementation hacks specified in section 5.2 [Retaining BNs and Explicit Formatting Characters](https://www.unicode.org/reports/tr9/#Retaining_Explicit_Formatting_Characters).
This fixes all of the character tests! (fixes #90). <s>We still have to fix some of the "basic" tests, which are unfortunately not as nicely labeled as the character tests.</s> This also fixes the basic tests (fixes https://github.com/servo/unicode-bidi/issues/8 )
This got mixed in with a bunch of other fixes since a lot of the code is nearby, a bunch of them fix things from N0. The main Big Fix in here besides the one around retaining explicit formatting is that the code now …

Handle retaining explicit formatting characters + other fixes

---

src/level.rs
src/lib.rs

To be able to use this over FFI I'd like to make this more explicitly transparent over u8.
I could also just mark it as transparent and let callers implement this, but I think offering it as an API is safer.

Add Level::from_slice_unchecked()

---

.rustfmt.toml
src/deprecated.rs
src/lib.rs

We were doing this extremely incorrectly: the correct algorithm does multiple overlaid reversals, similar to what we do below in `visual_runs` (though `visual_runs` has the benefit of operating on LevelRuns).
The test case this fixes is [`\u{202D}abc\u{202E}DEF\u{202D}ghi\u{202E}JKL\u{202D}mno`](https://util.unicode.org/UnicodeJsps/bidic.jsp?s=%E2%80%ADabc%E2%80%AEDEF%E2%80%ADghi%E2%80%AEJKL%E2%80%ADmno&b=2&u=140&d=2), which ought to get reordered as abcghimnoLKJFED, but instead does something different. There's also a simpler testcase in the doctest that already exists (so I didn't add this rather complicated case).

Fix implementation of L2 in reorder_visual

---

.github/workflows/main.yml

Fixes broken CI: syn 2.0 has a new MSRV
(We only depend on these for tests, but still)

Pin serde dep for MSRV build

---

src/lib.rs
tests/conformance_tests.rs

Fixes https://github.com/servo/unicode-bidi/issues/88
We now run the reordering part of the conformance tests. Good news: we already passed them all for `reorder_visual()`!. There was a small bug when it came to `visual_runs()` which took a bit of sleuthing but was easy to fix.

Run reordering conformance tests, more docs for reordering, fix bug

---

src/lib.rs

These two testcases in test_reordered_levels() are commented out with a TODO note, but if uncommented they appear to pass as written. So let's enable them, unless there's some reason not to?
(Or are they not believed to be correct tests?)

Uncomment tests BidiTest:69635 and BidiTest:291284.

---

Cargo.toml
benches/basic.rs
benches/udhr.rs
src/explicit.rs
src/implicit.rs
src/lib.rs
src/utf16.rs
tests/conformance_tests.rs

This aims to provide "native" UTF-16 support, with `*U16` versions of `InitialInfo`, `BidiInfo`, and `Paragraph` structs that are parallel to the existing types but work on a `[u16]` text buffer instead of a `str`.
Fixes https://github.com/servo/unicode-bidi/issues/108

UTF-16 support

---

src/lib.rs
src/utf16.rs

This gives us ParagraphBidiInfo and utf16::ParagraphBidiInfo structs, which work like BidiInfo but are explicitly single-paragraph APIs.
(If there's a paragraph separator present in the text, they'll simply treat it like a segment separator. An alternative would be to return some kind of error if this happens.... thoughts?)
I extended test_process_text() to also run its single-paragraph testcases through the new APIs, and also added a couple of tests of what happens when text with a paragraph separator is (erroneously) passed here, to confirm that we handle it as expected.

[para-api] Create ParagraphBidiInfo structs as API for processing a single paragraph at a time

---

src/prepare.rs

Fixes #119
Spec's a bit confusing here since it talks about this in the https://www.unicode.org/reports/tr9/#Retaining_Explicit_Formatting_Characters entry for X10, but the algorithm being tweaked is actually BD13, which X10 invokes.
This will be fixed once I actually clean things up.

Skip over X9 characters when calculating end classes for isolating_run_sequences().

---

src/lib.rs

The get_base_direction function (from #117) considers only the first paragraph of the given text; but if this has no strong characters, some callers may want to consider subsequent paragraphs as well rather than just return Mixed.
This is trivial to implement by simply resetting the isolate count when encountering a block separator, instead of returning at that point.
(It might've been better to expose a first_paragraph_only boolean parameter to the original get_base_direction, but I presume we don't want to modify public API, hence the separate ...full version of the function, sharing the internal implementation.

Provide get_base_direction_full API to consider the whole text

---

.github/workflows/main.yml

This PR updates outdated and replaces unmaintained actions in the GitHub Actions workflows.
The following updates are performed:
* update [`actions/checkout`](https://github.com/actions/checkout) to v4
* replace [unmaintained](https://github.com/actions-rs/toolchain/issues/216) `actions-rs/toolchain` by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain)
* replace unmaintained `actions-rs/cargo` by direct invocation of `cargo`
Still using the outdated / unmaintained actions will generate several warnings in CI runs, for example in https://github.com/servo/unicode-bidi/actions/runs/7561082906:
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions-rs/toolchain@v1, actions-rs/cargo@v1. For more info: …

Update GitHub Actions CI

---

Cargo.toml

We enforce this in CI, we should mention this in Cargo.toml.

Add MSRV line

---

.github/workflows/main.yml
Cargo.toml
src/char_data/mod.rs
src/char_data/tables.rs
src/deprecated.rs
src/explicit.rs
src/implicit.rs
src/level.rs
src/lib.rs
src/prepare.rs
src/utf16.rs

Hi! Thank you so much for this package, probably one of the most reliable Unicode bidi libraries I've ever discovered.
The following pull request cleans up the codebase by addressing (most) clippy warnings while also cleaning up other things i've noitced too. Like:
- Using `matches!` over manual `match` or `if let` statements.
- Simplify while-loop and for-loop definitions.
- Using `.find(...)` over `.filter(...).next()`.
- Using `.flatten()` for some nested for-loops.
- Remove `DirectionalStatusStack` as it's only used in one function in the codebase, and basically a wrapper over a `Vec<Status>` that doesn't do anything different.
If you have any feedback regarding this pull request, feel free to tell me! Cheers!

refactor: address clippy warnings + code cleanup

---

Cargo.toml
src/implicit.rs
src/lib.rs

We have some temporary vectors used during processing that will usually only hold a few entries. By using TinyVec here, we can avoid extra heap allocations in common cases.
(In Gecko's usage, I'm seeing around 4% improvement on the bidi- resolution subtest of perf_reftest_singletons with this change.)

[smallvec] Use SmallVec for some internal scratch vectors

---

src/deprecated.rs
src/explicit.rs
src/implicit.rs
src/level.rs
src/prepare.rs

This enables use of SmallVec for some more temporary vectors, to reduce heap allocations in common cases.
Also a couple of cosmetic clean-ups noticed in passing (which have no functional impact).

More use of SmallVec

---

src/explicit.rs
src/lib.rs
src/prepare.rs
src/utf16.rs

If there aren't any bidi isolation control characters in the paragraph, each level run directly corresponds to one isolating run sequence. (See notes under https://www.unicode.org/reports/tr9/#BD13.) In this case we can take a simplified codepath to process them.
Also, we can avoid the need for a separate pass over the levels array to find level runs by collecting the level runs at the same time as the levels array is being set up, during explicit::compute().

Use a simplified codepath if no bidi isolation controls are present.

---

.github/workflows/main.yml

This is in line with a new policy for the Servo organization discussed by the Servo TSC. We consider main to be easier to type, friendlier, and more modern so we are standardizing on this branch name for all projects in the organization.

Rename `master` branch to `main`

---

src/lib.rs

Fixes #138 
Set all bytes of char to prev_level.

Fix char boundary bug
